server:
  port: 65535

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.chyscor.mongodb.net/movie_review
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
      cors:
        allowed-origins: "*"